### ISSUE TITLE
Comparison with natestrauser's package

### ISSUE THREAD

**Issue by dandv** [meteor-singapore/font-awesome#1]
How is this package different from @nate-strauser's https://atmospherejs.com/natestrauser/font-awesome, which appears to be far more popular, better documented, and more up-to-date?

In case this package was just an experiment, you can hide it from Atmosphere searches with:

```
meteor admin set-unmigrated maxlibin:font-awesome
```

Thank you for keeping Atmosphere clean,
Dan

**Comment by maxlibin** [comment]
done!
